"""
Demo/inference.py

Loads model, data, and pre-computed evaluation results once on startup.

Data sources:
  - flair_80_10_10.pt         : trained model checkpoint (80/10/10 split)
  - scores_80_10_10.csv       : pre-computed anomaly scores for all 114,957 test windows,
                                 generated by evaluate_split.py with flair_80_10_10.pt.
                                 Columns: window_idx, anomaly_score, y_true, y_type
  - preprocessed.npz          : full dataset (X_num, X_cat) for live forward passes
                                 (needed for latent vector, reconstruction, and embedding
                                  fusion visualizations — these are computed live per window)

Threshold: 0.322566 — p99 of normal validation scores, from metrics_80_10_10.txt.
This matches the scores in scores_80_10_10.csv exactly (same model, same evaluation run).
"""

from __future__ import annotations

from pathlib import Path
from typing import Dict, List, Literal

import numpy as np
import pandas as pd
import torch
import yaml

from src.training.evaluate_flair import load_checkpoint


# ---------------------------------------------------------------------------
# Module-level state — populated once by _load_all()
# ---------------------------------------------------------------------------

_state: Dict = {}


def _load_all(config_path: str = "config.yaml") -> None:
    """Load model, data, and pre-computed 80/10/10 test-set scores."""
    if _state:
        return

    with open(config_path, "r", encoding="utf-8") as f:
        cfg = yaml.safe_load(f)

    _p = cfg.get("paths", {})
    npz_path    = str(_p.get("processed_npz", "data/processed/preprocessed.npz"))
    ckpt_path   = "experiments/results/flair_80_10_10.pt"
    scores_csv  = "experiments/results/scores_80_10_10.csv"

    # Threshold validated during the 80/10/10 evaluation run (metrics_80_10_10.txt)
    threshold = 0.322566

    device = torch.device("cpu")

    # -- Model --
    print("[demo] Loading model checkpoint (80/10/10)...")
    model, _ = load_checkpoint(ckpt_path, device)
    model.eval()

    # -- Dataset (memory-mapped for low RAM usage) --
    print("[demo] Memory-mapping dataset...")
    bundle = np.load(npz_path, allow_pickle=True)
    X_num  = bundle["X_num"].astype(np.float32)   # (N, 10, 21)
    X_cat  = bundle["X_cat"].astype(np.int64)     # (N, 10, 3)

    sport_vocab: dict = bundle["sport_vocab"][0]
    dport_vocab: dict = bundle["dport_vocab"][0]
    proto_vocab: dict = bundle["proto_vocab"][0]
    inv_sport = {v: k for k, v in sport_vocab.items()}
    inv_dport = {v: k for k, v in dport_vocab.items()}
    inv_proto = {v: k for k, v in proto_vocab.items()}
    num_features: List[str] = list(bundle["num_features"])

    # -- Pre-computed 80/10/10 test-set scores --
    # Generated by evaluate_split.py with flair_80_10_10.pt — consistent with threshold above.
    print("[demo] Loading 80/10/10 evaluation scores...")
    scores_df   = pd.read_csv(scores_csv)
    test_idx    = scores_df["window_idx"].values.astype(np.int64)    # global window indices
    scores_arr  = scores_df["anomaly_score"].values.astype(np.float32)
    y_true_arr  = scores_df["y_true"].values.astype(np.int64)
    y_type_arr  = scores_df["y_type"].values                         # object array of strings

    # Fast lookup: global window_idx → position in the test arrays
    idx_to_pos  = {int(wi): i for i, wi in enumerate(test_idx)}

    print(f"[demo] Test set: {len(test_idx):,} windows | "
          f"threshold: {threshold:.6f}")

    _state.update({
        "model":       model,
        "device":      device,
        "X_num":       X_num,
        "X_cat":       X_cat,
        "inv_sport":   inv_sport,
        "inv_dport":   inv_dport,
        "inv_proto":   inv_proto,
        "num_features": num_features,
        "threshold":   threshold,
        "test_idx":    test_idx,       # (114957,) global window indices
        "scores_arr":  scores_arr,     # (114957,) anomaly scores
        "y_true_arr":  y_true_arr,     # (114957,) 0/1 labels
        "y_type_arr":  y_type_arr,     # (114957,) attack type strings
        "idx_to_pos":  idx_to_pos,     # dict: global idx → array position
    })


def ensure_loaded(config_path: str = "config.yaml") -> None:
    _load_all(config_path)


# ---------------------------------------------------------------------------
# Public accessors
# ---------------------------------------------------------------------------

def get_threshold() -> float:
    ensure_loaded()
    return _state["threshold"]


def get_test_indices() -> np.ndarray:
    ensure_loaded()
    return _state["test_idx"]


def get_labels() -> np.ndarray:
    """Labels for the test set (same order as get_test_indices())."""
    ensure_loaded()
    return _state["y_true_arr"]


def get_indices(filter_mode: Literal["All", "Normal", "Attack"] = "All") -> np.ndarray:
    """Return global window indices for test-split windows matching the filter."""
    ensure_loaded()
    test_idx   = _state["test_idx"]
    y_true_arr = _state["y_true_arr"]
    if filter_mode == "Normal":
        return test_idx[y_true_arr == 0]
    elif filter_mode == "Attack":
        return test_idx[y_true_arr == 1]
    return test_idx


# ---------------------------------------------------------------------------
# Per-window inference
# ---------------------------------------------------------------------------

def run_inference(window_idx: int) -> Dict:
    """
    Run a live forward pass for one window, combining pre-computed scores
    with real-time model outputs for visualization.

    Pre-computed (from scores_80_10_10.csv, generated with flair_80_10_10.pt):
        anomaly_score, ground_truth, window_type

    Computed live (forward pass through flair_80_10_10.pt):
        fused_input  (10, 45)  — embedded categorical + numeric GRU input
        latent       (128,)    — encoder hidden state
        x_hat_num    (10, 21)  — decoder reconstruction
        per_feat_err (21,)     — MSE per feature

    Returns a dict with all of the above plus threshold, is_attack,
    cat_decoded, and num_features.
    """
    ensure_loaded()

    model:  torch.nn.Module = _state["model"]
    device: torch.device    = _state["device"]
    X_num:  np.ndarray      = _state["X_num"]
    X_cat:  np.ndarray      = _state["X_cat"]

    x_num_np = X_num[window_idx]  # (10, 21)
    x_cat_np = X_cat[window_idx]  # (10, 3)

    x_num_t = torch.from_numpy(x_num_np).unsqueeze(0).to(device)  # (1, 10, 21)
    x_cat_t = torch.from_numpy(x_cat_np).unsqueeze(0).to(device)  # (1, 10, 3)

    with torch.no_grad():
        out     = model(x_num_t, x_cat_t)
        fused_t = model._combine_inputs(x_num_t, x_cat_t)  # (1, 10, 45)

    x_hat_np  = out["x_hat_num"].squeeze(0).cpu().numpy()   # (10, 21)
    latent_np = out["latent"].squeeze(0).cpu().numpy()       # (128,)
    fused_np  = fused_t.squeeze(0).cpu().numpy()             # (10, 45)

    per_feat_err = np.mean((x_hat_np - x_num_np) ** 2, axis=0)  # (21,)

    # Look up pre-computed score and metadata (consistent with published metrics)
    pos          = _state["idx_to_pos"][window_idx]
    score        = float(_state["scores_arr"][pos])
    threshold    = _state["threshold"]
    ground_truth = int(_state["y_true_arr"][pos])
    window_type  = str(_state["y_type_arr"][pos])

    inv_sport = _state["inv_sport"]
    inv_dport = _state["inv_dport"]
    inv_proto = _state["inv_proto"]

    cat_decoded: List[Dict] = []
    for t in range(x_cat_np.shape[0]):
        sport_id, dport_id, proto_id = (
            int(x_cat_np[t, 0]),
            int(x_cat_np[t, 1]),
            int(x_cat_np[t, 2]),
        )
        cat_decoded.append({
            "Sport": inv_sport.get(sport_id, f"UNK({sport_id})"),
            "Dport": inv_dport.get(dport_id, f"UNK({dport_id})"),
            "Proto": inv_proto.get(proto_id, f"UNK({proto_id})"),
        })

    return {
        "x_num_raw":    x_num_np,
        "x_cat_raw":    x_cat_np,
        "fused_input":  fused_np,
        "latent":       latent_np,
        "x_hat_num":    x_hat_np,
        "per_feat_err": per_feat_err,
        "anomaly_score": score,
        "threshold":    threshold,
        "is_attack":    score > threshold,
        "ground_truth": ground_truth,
        "window_type":  window_type,
        "cat_decoded":  cat_decoded,
        "num_features": _state["num_features"],
    }
